#+title: Todo

* Now
- [-] Space Invaders example
  - [X] parse aseprite json
  - [X] animations
  - [X] collisions
    - [X] lose if enemy reaches the bottom
    - [X] lose if enemy touches the player
  - [ ] bullet
    - [ ] track enemy damage
    - [ ] remove dead enemy
    - [ ] blinking death animation
  - [ ] full game loop
    - [ ] title screen/intro reel
    - [ ] game over screen
      - [ ] score
  - [ ] bomb?
  - [ ] destructible shields?

- [-] SDF 2D example
  [[https://danielchasehooper.com/posts/code-animated-rick]]
  - [X] add fullscreen quad/triangle
  - [X] super-sampling
  - [ ] complete the examples
    - fill in all the necessary primitives
  - [ ] add a custom final example

* Next
- [ ] fix sprite drawing on windows - only drawing one sprite per frame
  - only the first sprite is always drawn (including when sprites are re-sorted)
  - removing depth entirely does not affect the behavior at all

- [ ] set up dioxus' hot patching

- [ ] sort sprites by 'object' position instead of 'sprite' position
  - this will matter for small sprites like the projectiles
  - could add a 'draw order' field to the gpu sprite itself

- [ ] descriptor set sizes are wrong when mixing storage buffers with uniform buffers
- [ ] binding multiple textures results in only being able to sample the first one
  is this a reflection problem, or a renderer descriptor set problem?

- [X] why is this tutorial renderer so much slower than SDL_gpu at sprites?
  it looks like it was the linear filtering by default instead of nearest

- [ ] remove per-frame duplication of non-image resources
  https://docs.vulkan.org/guide/latest/common_pitfalls.html#_resource_duplication_per_swapchain_image

- [ ] simplify basic triangle example
  use an orthographic projection instead of mvp?

- [ ] come up with a nicer way to handle different draw calls
  - ie, cmd_draw vs cmd_draw_indexed vs *_indirect variants
    want to be able to pass the counts directly
  - the enum is awkward to deal with
    and it's better not to store the counts
  - can the enum be fine if you fall back to a default transparent sprite/sdf?
    ie, for VertexCount basic cmd_draw call with a stored count

- [ ] add docs to Resources fields
  - explain the different draw call types
    ie, why vertex_count shows up and that it should be a multiple of 3
    maybe change it to 'triangle count' and do the mult?
    or make different topology options available besides triangle list

- [ ] support more parameter types
  - [ ] write-only storage buffers (StructuredBuffer)
  - [ ] read-write storage buffers (RWStructuredBuffer)
  - [ ] push constants?

- [ ] 3D signed distance fields / Shape Up clone
  - requires read/write storage buffers (for gpu-based object picking)

- [ ] sprite batch example from SDL_gpu

- [ ] is align(16) doing the right thing for Vertex?
 or is it doing anything?
- [ ] do we not have to be doing align(16)?
  - an extension promoted in 1.2 allows not using 16-byte alignment
    https://www.reddit.com/r/vulkan/comments/1dlvapz/problems_with_memory_layout_in_storage_buffer/l9t99ba/
    https://www.reddit.com/r/vulkan/comments/u5jiws/glsl_std140_layout_for_arrays_of_scalars/
  - see VK_KHR_uniform_buffer_standard_layout and VK_EXT_scalar_block_layout
- [ ] add tests or static assertions for matching struct layout

- [-] handle slang modules in codegen
 ie, allow a shared MVPMatrices type
  - [X] use a suffix to designate which slang files are shaders
  - [X] move MVP types to a module
  - [ ] generate a single rust type for the module
    https://discord.com/channels/1303735196696445038/1437915884034326608/1437915884034326608
    got no response; is there a workaround?
    - recognize when an equivalent struct is generated multiple times
      move all shared rust structs to one shared rust module
  - [ ] handle y-axis inversion and column-major transpose in the shared type

- [ ] post a request for SDL_gpu to support later vulkan versions
 do I plan on using that, or continuing with vulkan?
 sticking with vulkan:
  - bindless textures; buffer device addresses
  - avoiding std140 layout / weird hlsl constant buffer rules
    ie use the scalar_block_layout extension
  using SDL_gpu:
  - easier mac support
  - quicker to implement
  - access to SDL/MoonWorks community support

- [ ] PR to slang docs for pipeline builders example fixes
 see docs_notes.org
  - [ ] ask in discord about skipping nested ParameterBlocks

- [ ] read through shader cursor docs
 https://docs.shader-slang.org/en/latest/shader-cursors.html
 can we do a strongly-typed version of this?

- [ ] go through 'learn opengl' with this renderer
- [ ] do the official vulkan compute shader tutorial
 make it one of the examples here
- [ ] 3D SDF example
 https://www.youtube.com/watch?v=-Xb3Kk3HhIw

- [ ] add assertions/tests that struct fields are laid out correctly
  - this needs a more complex example, probably with nested structs
    align(16) solves the problem for the depth texture shader
  - what's the right way to get the size of a vector or matrix?
    slang gives us an index and count rather than a size & offset
    std::mem::size_of::<glam::Vec3>() ?
    the offset_of! macro?
    it seems like these would be testing the code against my guess at the layout,
    rather than against the actual layout
  - assert on order before writing generated source (leave the game runnable)
  - unit test this with a 'bad' slang file

- [ ] change ShaderAtlasEntry to allow optional vert/frag entry points
  how does that work with vertex descriptions

- [ ] split GPUWrite into different traits
  create_uniform_buffer should only take types declared in uniform   buffers
  storage buffers have a different layout convention

- [ ] handle shaders with different entry points in reflection
  ie, only compute, only fragment, etc

- [ ] add cargo feature flags
  - [ ] build-from-source-static for sdl3 on windows
  - [ ] shader hot reload for notify & shader_slang
    - [ ] figure out if slang precompile needs to be a workspace crate or something
- [ ] use a config module or cli params for stuff like COLUMN_MAJOR?

- [ ] handle nested ParameterBlocks
  - [ ] should add_descriptor_range also skip ParameterBlock like PushConstant?
    if we don't, it changes the binding numbers assigned to the double-wrapped items,
    which seems wrong
    but that actually happens if we early return there as well? is something else wrong?
    also, does slang even support nested ParameterBlocks right now

- [ ] slang reflection codegen
  - [ ] does create_descriptor_sets overwrite what we want to reflect?
    ie, with update_descriptor_sets in the loop
    - still need the texture sampler & image view somehow
      could get these fields from slang user attributes?
    - need to hold on to reflected data in shader module, merge with updates?
    - other resource-related things (ie, the image)
      will have to be handled by generated rust methods
  - [ ] handle regenerated binding code in dev mode somehow
    - just panic for now
    - later, move compilation to a background thread
      send a message to rebuild the pipeline
      need some way to ensure hot reload of the rust/script happens first
      use hash of input shader source in output dir for dependency tracking?

- [X] Figure out Windows HDR / SRGB bug
  why does TEXTURE_IMAGE_FORMAT need to be unorm on windows?
  is it my monitor or graphics card, or the OS?
  is there a 'proper' way to detect what it should be at runtime?
  - could be similar to this wgpu bug?
    https://github.com/gfx-rs/wgpu/issues/4842#issuecomment-1858018132
  it was incorrect alpha blending somehow - default color mask behavior is bad?

- [ ] split shader println into its own example
- [ ] split up depth texture & viking room shaders

- [ ] add a way to make storage buffers and/or textures cpu-readable
  this is useful for gpu-driven mouse 'picking'

* Future
- [ ] migrate off of anyhow
  - use thiserror for game api
  - use miette or a similar crate internally
    is it possible to get structured data (ie line numbers) out of slangc?

- [ ] is there a nice way to use slang's reinterpret<T> in codegen?
  ie, use an attribute to declare color format for a type
  https://docs.shader-slang.org/en/latest/external/slang/docs/user-guide/03-convenience-features.html#reinterpret-t-operation

- [ ] read about dynamic rendering
  - [ ] sascha's 1.3 triangle
  - [ ] vkguide?

- [ ] docs with panics sections for 'Storage' types
  - unwraps rely on the handles being unique and consumable
  - generics enforced by renderer module

- [ ] look into reflection-based codegen for bindless shaders
  https://discord.com/channels/1303735196696445038/1427662446579024013/1427662446579024013

- [ ] global param usage by entry point
  https://discord.com/channels/1303735196696445038/1428804639523868794/1428919601688871075
  this would fix using stage 'all'

- [ ] rewrite renderer in a new repo
  how much of this could be done gradually in this one?
  - use a cargo workspace
    make it easy to keep multiple working examples
    allow running codegen for a game crate that doesn't compile
  - group one-time initialized fields into a sub-struct w/methods
  - group sync primitive arrays with their resources in some way
    ie make it clear what's per-swapchain-image vs per-in-flight-frame
  - use an env var for vulkan validation layer
    https://github.com/ash-rs/ash/issues/190#issuecomment-758269723
    maybe for logging too? ie always compile w/verbose
  - also switch to dynamic rendering?
    in the future, try out bindless with slang support
  - maybe pregenerate mipmaps offline instead of doing it in vulkan at runtime
    can image-rs do this? need to pack them as well
    see if theres an stb tool or something

- [ ] make a spinning cube from scratch in slang

- [ ] set up switching between intel & nvidia graphics w/POP_OS?
  - [ ] figure out why it started using intel graphics
  - [ ] make sure the code is choosing a dedicated graphics card if it's availble

- [ ] vulkan-tutorial extras
  - [ ] compute shader

- [ ] look at Sascha Willems' other examples
- [ ] move on to https://vkguide.dev/ ?
  - use egui w/ash crate

- [ ] consider adding a separate queue & command buffer for memory transfer
  https://docs.vulkan.org/tutorial/latest/04_Vertex_buffers/02_Staging_buffer.html#_transfer_queue

- [ ] learn how to use a gpu memory allocator
  particularly the two crates the ash egui crate integrates with
- [ ] start recreating bevy 2d platformer with this tech stack?

- [ ] find out if hot-reloading pipeline code is possible
  ie, use lifecycle methods from

- [ ] understand stage & access masks better
  - [ ] review usage in ImageMemoryBarrier & in SubpassDependency
  re: creating framebuffers using the same depth image:
  "The color attachment differs for every swap chain image, but the same depth image can be used by all of them because only a single subpass is running at the same time due to our semaphores."
  so we'd need to do a depth image per swapchain image if there were multiple subpasses using them?
  how does SDL3_gpu handle that?
- [ ] review how barriers are used in the mipmap chapter

- [ ] try out using draw indirect & gpu culling

- [ ] generate build-time mipmaps
  - [ ] generate & use separate half-sized files with image-rs
  - [ ] combine & use into one packed sheet

- [ ] regenerate reflection structs during hot reload

- [ ] see if it's possible to use slang-rs compiler options CapabilityID
  instead of cli-style profile '+spirv_1_5'

- [ ] better printf and validation layers setup
  control the validation layers with env vars
  use the env vars described here:
  https://www.lunarg.com/wp-content/uploads/2021/08/Using-Debug-Printf-02August2021.pdf

- [ ] try to avoid the vk::ShaderStageFlags::ALL in add_global_scope_parameters
  - is there a way to use reflection to get at the true usage?
    #+begin_quote
    Applications that want to set more precise stage flags, taking into account which data is accessed by which stages in the compiled program binary, are encouraged to look at the more comprehensive documentation on the reflection API.
    #+end_quote
    https://docs.shader-slang.org/en/latest/parameter-blocks.html#global-scope
    there is reference to this in the slangc json code;
      there are steps after/if codegen was done

- [ ] handle unbounded count in bindings (bitwise not 0)
  see SLANG_UNBOUNDED_SIZE
  https://github.com/shader-slang/slang/blob/04093bcbaea9784cdffe55f3931f50db7ad9f808/source/slang/slang-reflection-json.cpp#L124
  https://github.com/shader-slang/slang/blob/04093bcbaea9784cdffe55f3931f50db7ad9f808/include/slang.h#L2167

- [ ] document that ParameterBlock element must always be a struct
  ie Platform<Matrix4x4> is not supported; there must be a wrapper

- [ ] look into slang user attributes
  https://discord.com/channels/1303735196696445038/1387610899787022438/1387610899787022438
  https://discord.com/channels/1303735196696445038/1419640000609386496/1420377508683186258
  https://discord.com/channels/1303735196696445038/1305995870046650368/1410741801467510867
  - how to implement? the playground examples use typescript & webgpu
    https://github.com/shader-slang/slang-playground/blob/1b97fa8bdf2a6cb2b18ca2d8e8d5e4b54b6eba51/public/demos/image-from-url.slang
    https://github.com/shader-slang/slang-playground/blob/main/engine/slang-compilation-engine/src/slang/playground.slang

- [ ] move the vk color format restriction on entry point fields out of codegen
  make the enum of supported glam types / primitives part of StructEntryPointParameter

- [ ] replace ReflectionJson::layout_bindings with directly inlining data in generated code


* Roc Questions
- [ ] are ref-counted platform resource heaps still going to be a thing?
- [ ] will compiler apis be available for compile-time reflection by platforms?
- [ ] will there be some way to say "I'm trying to implement this interface"
  like to get nicer error messages
