#!/usr/bin/env bash
#
# Regenerate platform/LICENSES from the toolchain and the dependency graph.
#
# The bundle is a redistributed artifact. It carries a copy of libstdc++.a,
# three glibc startup objects, and a libhost.a that statically links SDL3,
# slang and about 140 rust crates. Each of those carries an attribution
# requirement, so the licence texts ship inside the archive beside
# platform/NOTICE.
#
# Every text here is a copy of a file the build already has: the distro
# copyright files, SDL's own LICENSE.txt, the licences the slang tarball
# ships, and a table derived from cargo metadata. Nothing is hand-written,
# so nothing drifts from the binaries.

set -euo pipefail
export LC_ALL=C
cd "$(dirname "$0")/.."

TRIPLE=x86_64-unknown-linux-gnu
OUT=platform/LICENSES

fail() {
    echo "Error: $*" >&2
    exit 1
}

for tool in jq cargo dpkg-query; do
    command -v "$tool" > /dev/null 2>&1 || fail "$tool is not on PATH."
done

# --- inputs ------------------------------------------------------------------

GCC_COPYRIGHT=/usr/share/doc/libstdc++-13-dev/copyright
GLIBC_COPYRIGHT=/usr/share/doc/libc6-dev/copyright
[ -r "$GCC_COPYRIGHT" ] || fail "$GCC_COPYRIGHT is missing (install libstdc++-13-dev)."
[ -r "$GLIBC_COPYRIGHT" ] || fail "$GLIBC_COPYRIGHT is missing (install libc6-dev)."

# SDL3 compiles from source, so its tree sits in the cargo registry. The
# version comes from Cargo.lock, which is committed.
sdl3_version=$(awk '/^name = "sdl3-src"$/{found=1} found && /^version = /{gsub(/"/,"",$3); print $3; exit}' Cargo.lock)
[ -n "$sdl3_version" ] || fail "Cargo.lock names no sdl3-src version."
sdl3_license=$(find "$HOME/.cargo/registry/src" -maxdepth 4 \
    -path "*/sdl3-src-$sdl3_version/SDL/LICENSE.txt" 2> /dev/null | head -1)
[ -n "$sdl3_license" ] || fail "no LICENSE.txt for sdl3-src-$sdl3_version in the cargo registry."

# The slang tarball ships a licences tree for slang and every library it
# bundles. It unpacks into the build script's output directory.
slang_licenses=$(find "target/$TRIPLE/release/build" -maxdepth 5 \
    -path "*/slang-static/linux-x86_64/licenses" -type d 2> /dev/null | head -1)
[ -n "$slang_licenses" ] || fail "no slang licences tree under target/$TRIPLE/release/build (run build.sh first)."

# The slang release the tarball came from. The shader-slang tag carries it as
# build metadata, and Cargo.lock percent-encodes the plus.
slang_version=$(awk '/^name = "shader-slang"$/{found=1} found && /^source = /{print; exit}' Cargo.lock \
    | sed -n 's/.*%2B\(slang-[0-9.]*\)#.*/\1/p')
[ -n "$slang_version" ] || fail "Cargo.lock names no shader-slang tag with a slang version."

# --- copy --------------------------------------------------------------------

rm -rf "$OUT"
mkdir -p "$OUT"

install -m 644 LICENSE "$OUT/platform-UPL-1.0.txt"
install -m 644 "$GCC_COPYRIGHT" "$OUT/libstdc++-gcc.txt"
install -m 644 "$GLIBC_COPYRIGHT" "$OUT/glibc.txt"
install -m 644 "$sdl3_license" "$OUT/SDL3-Zlib.txt"

# Flattened, so bundle.sh needs one glob rather than a recursive walk.
for path in "$slang_licenses"/*; do
    name=$(basename "$path")
    if [ -d "$path" ]; then
        for nested in "$path"/*; do
            install -m 644 "$nested" "$OUT/slang-$name-$(basename "$nested")"
        done
    else
        install -m 644 "$path" "$OUT/slang-$name"
    fi
done

# --- generate ----------------------------------------------------------------

{
    echo "Every rust crate in this platform's dependency graph, with the licence"
    echo "its manifest declares. libhost.a statically links the code of those"
    echo "crates that reach the host. Generated by ci/licenses.sh from"
    echo "cargo metadata --locked."
    echo ""
    cargo metadata --format-version 1 --locked \
        | jq -r '.packages[] | [.name, .version, (.license // "see " + (.repository // "the crate manifest"))] | @tsv' \
        | sort -u \
        | awk -F'\t' '{printf "  %-34s %-18s %s\n", $1, $2, $3}'
} > "$OUT/rust-crates.txt"

{
    echo "The source package of every third-party file in this directory and in"
    echo "targets/x64glibc. Generated by ci/licenses.sh."
    echo ""
    printf '  %-24s %s\n' "libstdc++.a" "$(dpkg-query -W -f='${Package} ${Version}' libstdc++-13-dev)"
    printf '  %-24s %s\n' "Scrt1.o crti.o crtn.o" "$(dpkg-query -W -f='${Package} ${Version}' libc6-dev)"
    printf '  %-24s %s\n' "SDL3" "sdl3-src $sdl3_version"
    printf '  %-24s %s\n' "slang" "$slang_version"
} > "$OUT/SOURCES.txt"

echo "Wrote $(find "$OUT" -type f | wc -l) files to $OUT."
