[package]
name = "watercolor"
version.workspace = true
edition.workspace = true
publish = false
default-run = "watercolor"

[lints]
workspace = true

[dependencies]
mltrs.workspace = true

anyhow.workspace = true
facet.workspace = true
glam.workspace = true

# named directly by the generated shader bindings
ash.workspace = true
serde.workspace = true
serde_json.workspace = true

image.workspace = true
