[package]
name = "mltrs-renderer"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
mltrs-slang-reflection.workspace = true

anyhow.workspace = true
ash.workspace = true
egui.workspace = true
egui-ash-renderer.workspace = true
facet.workspace = true
facet-core.workspace = true
glam.workspace = true
heck.workspace = true
log.workspace = true
notify.workspace = true
sdl3.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
vk-mem.workspace = true
