#!/bin/bash
set -eo pipefail

# The host links SDL3, the Vulkan loader, and the C++ runtime that slang and
# vk-mem need. Those are glibc-linked on this machine, so the platform builds
# for x64glibc only. musl and macOS targets need a static Vulkan/SDL story that
# does not exist here.
#
# roc resolves every name in a target's `inputs` list against
# platform/targets/<target>/. Everything there except libhost.a is committed and
# generated by stubs/generate.sh, so this script needs no compiler: it checks the
# inputs are present and builds the archive.

TARGET_NAME=x64glibc
RUST_TRIPLE=x86_64-unknown-linux-gnu
TARGET_DIR="platform/targets/$TARGET_NAME"

# Every input the x64glibc inputs list names, except libhost.a and app.
COMMITTED_INPUTS=(
    Scrt1.o
    crti.o
    crtn.o
    force_extract.o
    libstdc++.a
    libvulkan.so
    libm.so
    libc.so
    libc_forward.a
    libgcc_s.so
)

arch=$(uname -m)
os=$(uname -s)
if [ "$os" != "Linux" ] || [ "$arch" != "x86_64" ]; then
    echo "Unsupported host: $os $arch (this platform builds x64glibc only)" >&2
    exit 1
fi

missing=()
for name in "${COMMITTED_INPUTS[@]}"; do
    [ -f "$TARGET_DIR/$name" ] || missing+=("$name")
done
if [ ${#missing[@]} -ne 0 ]; then
    echo "Missing committed link inputs in $TARGET_DIR:" >&2
    printf '  %s\n' "${missing[@]}" >&2
    echo "Regenerate them with \`just roc-platform stubs\`." >&2
    exit 1
fi

echo "Building for $TARGET_NAME ($RUST_TRIPLE)..."
cargo build --release --lib --target "$RUST_TRIPLE"

cp "target/$RUST_TRIPLE/release/libhost.a" "$TARGET_DIR/"
echo "  -> $TARGET_DIR/libhost.a"

echo ""
echo "Build complete!"
