# Asset-free unittest suite for the Link animation tooling, run by
# `just toon_link link-test-animations` via run_tests.py. Requires uv to
# resolve the pinned gclib dependency (run_tests.py fails clearly without
# it). No game assets: every fixture is generated by gen_fixtures.py.

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = TESTS_DIR.parent
sys.path.insert(0, str(SCRIPTS_DIR))
sys.path.insert(0, str(TESTS_DIR))

import extract_link_animations as ex  # noqa: E402
import gen_fixtures as fx  # noqa: E402

CL_MATERIALS = ["ear", "eyeL", "eyeR", "face", "mayuL", "mayuR", "mouth", "sleeve"]


def sample_members(joint_count: int = 42) -> dict[str, bytes]:
    """A small but representative archive set: an included BCK, a prop BCK
    (wrong joint count), an included BTP, an out-of-scope BTP (foreign
    materials), an included BTK, a prop BTK, and one out-of-scope directory
    (bpk) that must never be extracted."""
    bck_ok = fx.j3d_file(b"bck1", fx.bck_chunk([[fx.default_axis()] * 3 for _ in range(joint_count)]))
    bck_prop = fx.j3d_file(b"bck1", fx.bck_chunk([[fx.default_axis()] * 3 for _ in range(5)]))
    btp_ok = fx.j3d_file(
        b"btp1",
        fx.btp_chunk(
            [
                {"material": "mouth", "remap": 14, "texno": 0, "samples": [27, 7, 7]},
                {"material": "mouth", "remap": 14, "texno": 0, "samples": [9]},
            ]
        ),
    )
    btp_foreign = fx.j3d_file(
        b"btp1",
        fx.btp_chunk([{"material": "ItemGet_mouth", "remap": 0, "texno": 0, "samples": [1]}]),
    )
    btk = dict(
        material="eyeL",
        remap=7,
        texgen=2,
        center=[0.5, -0.5, 0.25],
        axes=[fx.default_axis()] * 3,
        scale_pool=[1.0, 2.0, 3.0],
        rotation_pool=[0x4000],
        translation_pool=[0.0, 0.0, 0.0, 0.25, 5.0, 1.0, 0.5, 0.125] * 3,
    )
    btk_ok = fx.j3d_file(b"btk1", fx.btk_chunk([btk]))
    btk["material"] = "lightSaver"
    btk_prop = fx.j3d_file(b"btk1", fx.btk_chunk([btk]))
    return {
        "bcks/a_ok.bck": bck_ok,
        "bcks/prop.bck": bck_prop,
        "btp/face.btp": btp_ok,
        "btp/foreign.btp": btp_foreign,
        "btk/scroll.btk": btk_ok,
        "btk/prop.btk": btk_prop,
        "bpk/junk.bpk": b"\0PKJ" + b"\0" * 64,
    }


class Harness(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        self.disc = self.root / "disc.ciso"
        self.disc.write_bytes(b"")
        self.dtk = fx.write_fake_dtk(self.root)
        self.fake_root = self.root / "vfs"
        self.fake_root.mkdir()
        for archive in ex.ARCHIVES:
            (self.fake_root / f"{archive}.arc").write_bytes(fx.rarc(sample_members()))
        (self.fake_root / "cl.bdl").write_bytes(fx.cl_bdl(42, CL_MATERIALS))
        self.out = self.root / "out"
        self.paths = {"tww": self.root, "disc": self.disc, "dtk": self.dtk}

    def run_extract(self, *args: str, env_extra: dict[str, str] | None = None) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env["TWW_DIR"] = str(self.root)
        env["FAKE_DTK_ROOT"] = str(self.fake_root)
        if env_extra:
            env.update(env_extra)
        proc = subprocess.run(
            [
                sys.executable,
                str(SCRIPTS_DIR / "extract_link_animations.py"),
                "--disc",
                str(self.disc),
                "--dtk",
                str(self.dtk),
                "--out-dir",
                str(self.out),
                *args,
            ],
            capture_output=True,
            text=True,
            env=env,
            cwd=self.root,
        )
        return proc

    def bootstrap(self) -> dict:
        proc = self.run_extract("--bootstrap")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        return json.loads((self.out / "candidate" / "selection.json").read_text())


class CheckoutEnvironment(Harness):
    def test_empty_checkout_fails_before_extraction(self) -> None:
        proc = self.run_extract("--bootstrap", env_extra={"TWW_DIR": ""})
        self.assertEqual(proc.returncode, 1)
        self.assertIn("Set TWW_DIR", proc.stderr)
        self.assertNotIn("Traceback", proc.stderr)
        self.assertFalse(self.out.exists())

    def test_missing_checkout_environment_fails(self) -> None:
        env = dict(os.environ)
        env.pop("TWW_DIR", None)
        for command in (
            [sys.executable, str(SCRIPTS_DIR / "extract_link_animations.py")],
            ["bash", str(SCRIPTS_DIR / "extract_link.sh")],
        ):
            with self.subTest(command=command):
                proc = subprocess.run(command, env=env, capture_output=True, text=True)
                self.assertNotEqual(proc.returncode, 0)
                self.assertIn("Set TWW_DIR", proc.stderr)
                self.assertNotIn("Traceback", proc.stderr)


class ExtractionScopeAndIdentity(Harness):
    """Check extraction scope and identity on synthetic fixtures.

    The verify driver checks the real inventory against the selection.
    """
    def test_exclusion_reasons_and_skipped_dirs(self) -> None:
        sel = self.bootstrap()
        entries = {(e["archive"], e["member"]): e for e in sel["entries"]}
        self.assertEqual(entries[("LkAnm", "bcks/a_ok.bck")]["classification"], "included")
        self.assertEqual(entries[("LkAnm", "bcks/a_ok.bck")]["reason"], "cl-skeleton-42-joints")
        self.assertEqual(entries[("LkAnm", "bcks/prop.bck")]["classification"], "excluded")
        self.assertIn("5-not-cl-42", entries[("LkAnm", "bcks/prop.bck")]["reason"])
        self.assertEqual(entries[("LkAnm", "btp/face.btp")]["classification"], "included")
        self.assertEqual(entries[("LkAnm", "btp/foreign.btp")]["classification"], "excluded")
        self.assertIn("no-cl-materials", entries[("LkAnm", "btp/foreign.btp")]["reason"])
        self.assertEqual(entries[("LkAnm", "btk/scroll.btk")]["classification"], "included")
        self.assertEqual(entries[("LkAnm", "btk/prop.btk")]["classification"], "excluded")
        report = json.loads((self.out / "candidate" / "extraction_report.json").read_text())
        # one bpk member in each of the three archives
        self.assertEqual(report["skipped_directories"], {"bpk": 3})
        # bpk members are never extracted
        self.assertFalse((self.out / "candidate" / "raw" / "LkAnm" / "bpk").exists())

    def test_identity_fields(self) -> None:
        self.bootstrap()
        inventory = json.loads((self.out / "candidate" / "raw" / "inventory.json").read_text())
        by_member = {(e["archive"], e["member"]): e for e in inventory["entries"]}
        self.assertIn(("LkAnm", "bcks/a_ok.bck"), by_member)
        entry = by_member[("LkAnm", "bcks/a_ok.bck")]
        self.assertEqual(entry["archive"], "LkAnm")
        self.assertGreaterEqual(entry["entry_index"], 0)
        self.assertEqual(entry["format"], "bck")
        self.assertEqual(entry["size"], entry["size"])
        self.assertRegex(entry["sha256"], r"^[0-9a-f]{64}$")
        # distinct identity per archive: every archive carries its own copy
        self.assertEqual(len({e["archive"] for e in inventory["entries"]}), 3)

    def test_mixed_scope_targets_are_a_hard_failure(self) -> None:
        mixed = fx.j3d_file(
            b"btp1",
            fx.btp_chunk(
                [
                    {"material": "mouth", "remap": 1, "texno": 0, "samples": [1]},
                    {"material": "sword_blade", "remap": 2, "texno": 0, "samples": [2]},
                ]
            ),
        )
        members = sample_members()
        members["btp/mixed.btp"] = mixed
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        proc = self.run_extract("--bootstrap")
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("mixed material targets", proc.stderr)

    def test_btk_post_set_membership_governs_scope(self) -> None:
        def btk_with(post_material: str | None) -> bytes:
            main = dict(
                material="eyeL",
                remap=0,
                texgen=0,
                center=[0.0, 0.0, 0.0],
                axes=[fx.default_axis()] * 3,
                scale_pool=[],
                rotation_pool=[],
                translation_pool=[],
            )
            post = None
            if post_material is not None:
                post = dict(
                    material=post_material,
                    remap=0,
                    texgen=0,
                    center=[0.0, 0.0, 0.0],
                    axes=[fx.default_axis()] * 3,
                    scale_pool=[],
                    rotation_pool=[],
                    translation_pool=[],
                )
            return fx.j3d_file(b"btk1", fx.btk_chunk([main], post_targets=[post] if post else None))

        # CL main targets + foreign post target: mixed scope, hard failure.
        members = sample_members()
        members["btk/post_mixed.btk"] = btk_with("lightSaver")
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        proc = self.run_extract("--bootstrap")
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("mixed material targets", proc.stderr)

        # CL main + CL post: included.
        members = sample_members()
        members["btk/post_ok.btk"] = btk_with("eyeR")
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        proc = self.run_extract("--bootstrap")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        inventory = json.loads((self.out / "candidate" / "raw" / "inventory.json").read_text())
        self.assertIn(
            "btk/post_ok.btk",
            {e["member"] for e in inventory["entries"]},
        )


class ExtractionRejectsUnsafePaths(Harness):
    """Reject unsafe paths during extraction."""
    def test_traversal_named_file_rejected(self) -> None:
        members = sample_members()
        members["bcks/..evil.bck"] = members.pop("bcks/a_ok.bck")
        # A file whose *name* contains a slash (i.e. a smuggled path)
        members["bcks/smug\\gled.bck"] = members["bcks/prop.bck"]
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        # The smuggled backslash is rejected by the path policy
        proc = self.run_extract("--bootstrap")
        self.assertNotEqual(proc.returncode, 0, proc.stdout)
        self.assertIn("unsafe path component", proc.stderr)


class ExtractionRepeatable(Harness):
    """Check that repeated extraction produces identical output."""
    def test_bootstrap_is_byte_identical(self) -> None:
        self.bootstrap()
        first = (self.out / "candidate" / "selection.json").read_bytes()
        hashes1 = (self.out / "candidate" / "link_animation_assets.sha256").read_bytes()
        self.bootstrap()
        self.assertEqual(first, (self.out / "candidate" / "selection.json").read_bytes())
        self.assertEqual(hashes1, (self.out / "candidate" / "link_animation_assets.sha256").read_bytes())


class GoldenGates(Harness):
    """Normal (non-bootstrap) runs against promoted goldens."""

    def promote(self, out_name: str = "goldens") -> tuple[Path, Path]:
        self.bootstrap()
        goldens = self.root / out_name
        goldens.mkdir()
        shutil.copy(self.out / "candidate" / "selection.json", goldens / "selection.json")
        lines = []
        for line in (self.out / "candidate" / "link_animation_assets.sha256").read_text().splitlines():
            digest, _, rel = line.partition("  ")
            lines.append(f"{digest}  assets/link/animations/raw/{rel.removeprefix('raw/')}")
        (goldens / "hashes.sha256").write_text("\n".join(lines) + "\n")
        return goldens / "selection.json", goldens / "hashes.sha256"

    def run_normal(self, selection: Path, hashes: Path):
        env = {"FAKE_DTK_ROOT": str(self.fake_root)}
        proc = self.run_extract("--selection", str(selection), "--hashes", str(hashes), env_extra=env)
        return proc

    def test_normal_run_succeeds_against_promoted_goldens(self) -> None:
        selection, hashes = self.promote()
        proc = self.run_normal(selection, hashes)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertTrue((self.out / "raw" / "inventory.json").is_file())

    def test_extraction_tamper_missing_and_extra_fail(self) -> None:
        selection, hashes = self.promote()

        # extra member appears in the archive
        members = sample_members()
        members["bcks/extra.bck"] = members["bcks/a_ok.bck"]
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        proc = self.run_normal(selection, hashes)
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("new member", proc.stderr)

        # member missing
        members = sample_members()
        del members["bcks/a_ok.bck"]
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        proc = self.run_normal(selection, hashes)
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("missing member", proc.stderr)

        # member altered (same identity, different bytes)
        members = sample_members()
        members["bcks/a_ok.bck"] = bytearray(members["bcks/a_ok.bck"])
        members["bcks/a_ok.bck"][-2] ^= 0xFF
        (self.fake_root / "LkAnm.arc").write_bytes(fx.rarc(members))
        proc = self.run_normal(selection, hashes)
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("altered", proc.stderr)

    def test_extraction_failure_preserves_previous_tree(self) -> None:
        selection, hashes = self.promote()
        proc = self.run_normal(selection, hashes)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        before = {p.relative_to(self.out): p.read_bytes() for p in (self.out / "raw").rglob("*") if p.is_file()}
        # break the source so the next run fails during classification
        (self.fake_root / "LkAnm.arc").write_bytes(b"RARC" + b"\0" * 64)
        proc = self.run_normal(selection, hashes)
        self.assertNotEqual(proc.returncode, 0)
        after = {p.relative_to(self.out): p.read_bytes() for p in (self.out / "raw").rglob("*") if p.is_file()}
        self.assertEqual(before, after)


class BootstrapIsExplicit(GoldenGates):
    """Require explicit bootstrap when golden files are absent."""
    def test_no_goldens_bootstrap_works_normal_fails(self) -> None:
        # No goldens in play: bootstrap must succeed and write only the
        # candidate tree; the production raw tree must not exist.
        proc = self.run_extract("--bootstrap")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertTrue((self.out / "candidate" / "raw" / "inventory.json").is_file())
        self.assertFalse((self.out / "raw").exists())

        # Normal mode with absent goldens fails and still publishes nothing
        # (explicit paths, so the test does not depend on whether the
        # production goldens in scripts/ have been promoted yet).
        missing = self.root / "absent-goldens"
        proc = self.run_extract(
            "--selection", str(missing / "selection.json"),
            "--hashes", str(missing / "hashes.sha256"),
        )
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("golden selection manifest", proc.stderr)
        self.assertFalse((self.out / "raw").exists())

    def test_bootstrap_never_touches_existing_goldens(self) -> None:
        selection, hashes = self.promote()
        before_sel = selection.read_bytes()
        before_hashes = hashes.read_bytes()
        proc = self.run_extract("--bootstrap")
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(before_sel, selection.read_bytes())
        self.assertEqual(before_hashes, hashes.read_bytes())

    def test_pre_promotion_pipeline_end_to_end(self) -> None:
        """The full bootstrap → convert → oracle pipeline over the candidate
        tree with goldens *absent*, proving the pre-promotion flow works and
        leaves the tracked goldens and production output untouched."""
        converter = os.environ.get("CONVERT_LINK_ANIMATIONS")
        if not converter:
            self.fail("CONVERT_LINK_ANIMATIONS is unset; the recipe must build the converter first")
        selection = self.root / "goldens-absent" / "selection.json"
        hashes = self.root / "goldens-absent" / "hashes.sha256"
        # Bootstrap with no goldens in play.
        proc = self.run_extract(
            "--bootstrap",
            "--selection", str(selection),
            "--hashes", str(hashes),
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        candidate_raw = self.out / "candidate" / "raw"
        self.assertTrue((candidate_raw / "inventory.json").is_file())

        # Convert the candidate tree; every clip must parse.
        converted = self.out / "candidate" / "converted"
        proc = subprocess.run(
            [converter, str(candidate_raw), str(converted)], capture_output=True, text=True
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        catalog = json.loads((converted / "catalog.json").read_text())
        self.assertGreater(len(catalog["clips"]), 0)

        # Oracle parity over the whole candidate tree, including the gclib
        # cross-check layer.
        sys.path.insert(0, str(SCRIPTS_DIR))
        import link_animation_oracle as oracle_mod

        dump = oracle_mod.dump_all(candidate_raw)
        rust = subprocess.run(
            [converter, str(candidate_raw), str(self.out / "unused"), "--dump-canonical"],
            capture_output=True,
            text=True,
        )
        self.assertEqual(rust.returncode, 0, rust.stderr)
        self.assertEqual(rust.stdout, dump)
        for e in json.loads((candidate_raw / "inventory.json").read_text())["entries"]:
            data = (candidate_raw / e["archive"] / e["member"]).read_bytes()
            oracle_mod.cross_check(data, e["format"], f"{e['archive']}/{e['member']}")

        # Goldens still absent, production raw still not published.
        self.assertFalse(selection.exists())
        self.assertFalse(hashes.exists())
        self.assertFalse((self.out / "raw").exists())


if __name__ == "__main__":
    unittest.main()
