[package]
name = "basic_triangle"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
mltrs.workspace = true

anyhow.workspace = true
ash.workspace = true
facet.workspace = true
glam.workspace = true
serde.workspace = true
serde_json.workspace = true
