# Stub shared object for libc.so.6. Generated by stubs/generate.sh.
#
# Declares the symbols the host archive leaves undefined, so the link
# resolves and the executable records libc.so.6 as a plain DT_NEEDED. The
# real library provides every implementation at run time. A symbol
# with a single version stays unversioned and carries no GLIBC_2.xx
# requirement. A symbol the library also exports at a compat version
# carries a .symver pin to the default version: ld.so binds an
# unversioned reference to the oldest version node, which is the
# compat implementation.
#
# glibc floor: 2.39. Toolchain: built_with_toolchain.txt.

.text
.balign 8
.globl _Exit
.type _Exit, @function
_Exit: ret

.balign 8
.globl __assert_fail
.type __assert_fail, @function
__assert_fail: ret

.balign 8
.globl __ctype_get_mb_cur_max
.type __ctype_get_mb_cur_max, @function
__ctype_get_mb_cur_max: ret

.balign 8
.globl __cxa_at_quick_exit
.type __cxa_at_quick_exit, @function
__cxa_at_quick_exit: ret

.balign 8
.globl __cxa_atexit
.type __cxa_atexit, @function
__cxa_atexit: ret

.balign 8
.globl __cxa_thread_atexit_impl
.type __cxa_thread_atexit_impl, @function
__cxa_thread_atexit_impl: ret

.balign 8
.globl __duplocale
.type __duplocale, @function
__duplocale: ret

.balign 8
.globl __errno_location
.type __errno_location, @function
__errno_location: ret

.balign 8
.globl __fdelt_chk
.type __fdelt_chk, @function
__fdelt_chk: ret

.balign 8
.globl __fprintf_chk
.type __fprintf_chk, @function
__fprintf_chk: ret

.balign 8
.globl __freelocale
.type __freelocale, @function
__freelocale: ret

.balign 8
.globl __getcwd_chk
.type __getcwd_chk, @function
__getcwd_chk: ret

.balign 8
.globl __isoc23_fscanf
.type __isoc23_fscanf, @function
__isoc23_fscanf: ret

.balign 8
.globl __isoc23_sscanf
.type __isoc23_sscanf, @function
__isoc23_sscanf: ret

.balign 8
.globl __isoc23_strtol
.type __isoc23_strtol, @function
__isoc23_strtol: ret

.balign 8
.globl __isoc23_strtoll
.type __isoc23_strtoll, @function
__isoc23_strtoll: ret

.balign 8
.globl __isoc23_strtoul
.type __isoc23_strtoul, @function
__isoc23_strtoul: ret

.balign 8
.globl __isoc23_strtoull
.type __isoc23_strtoull, @function
__isoc23_strtoull: ret

.balign 8
.globl __isoc23_vsscanf
.type __isoc23_vsscanf, @function
__isoc23_vsscanf: ret

.balign 8
.globl __isoc23_wcstol
.type __isoc23_wcstol, @function
__isoc23_wcstol: ret

.balign 8
.globl __iswctype_l
.type __iswctype_l, @function
__iswctype_l: ret

.balign 8
.globl __libc_current_sigrtmax
.type __libc_current_sigrtmax, @function
__libc_current_sigrtmax: ret

.balign 8
.globl __libc_current_sigrtmin
.type __libc_current_sigrtmin, @function
__libc_current_sigrtmin: ret

.balign 8
.globl __pin___libc_start_main
.type __pin___libc_start_main, @function
__pin___libc_start_main: ret
.symver __pin___libc_start_main, __libc_start_main@@GLIBC_2.34, remove

.balign 8
.globl __mbsnrtowcs_chk
.type __mbsnrtowcs_chk, @function
__mbsnrtowcs_chk: ret

.balign 8
.globl __mbsrtowcs_chk
.type __mbsrtowcs_chk, @function
__mbsrtowcs_chk: ret

.balign 8
.globl __mbstowcs_chk
.type __mbstowcs_chk, @function
__mbstowcs_chk: ret

.balign 8
.globl __memcpy_chk
.type __memcpy_chk, @function
__memcpy_chk: ret

.balign 8
.globl __memmove_chk
.type __memmove_chk, @function
__memmove_chk: ret

.balign 8
.globl __memset_chk
.type __memset_chk, @function
__memset_chk: ret

.balign 8
.globl __newlocale
.type __newlocale, @function
__newlocale: ret

.balign 8
.globl __nl_langinfo_l
.type __nl_langinfo_l, @function
__nl_langinfo_l: ret

.balign 8
.globl __openat_2
.type __openat_2, @function
__openat_2: ret

.balign 8
.globl __printf_chk
.type __printf_chk, @function
__printf_chk: ret

.balign 8
.globl __read_chk
.type __read_chk, @function
__read_chk: ret

.balign 8
.globl __register_atfork
.type __register_atfork, @function
__register_atfork: ret

.balign 8
.globl __res_init
.type __res_init, @function
__res_init: ret

.balign 8
.globl __snprintf_chk
.type __snprintf_chk, @function
__snprintf_chk: ret

.balign 8
.globl __sprintf_chk
.type __sprintf_chk, @function
__sprintf_chk: ret

.balign 8
.globl __stack_chk_fail
.type __stack_chk_fail, @function
__stack_chk_fail: ret

.balign 8
.globl __strcoll_l
.type __strcoll_l, @function
__strcoll_l: ret

.balign 8
.globl __strftime_l
.type __strftime_l, @function
__strftime_l: ret

.balign 8
.globl __strtod_l
.type __strtod_l, @function
__strtod_l: ret

.balign 8
.globl __strtof_l
.type __strtof_l, @function
__strtof_l: ret

.balign 8
.globl __strxfrm_l
.type __strxfrm_l, @function
__strxfrm_l: ret

.balign 8
.globl __tls_get_addr
.type __tls_get_addr, @function
__tls_get_addr: ret

.balign 8
.globl __towlower_l
.type __towlower_l, @function
__towlower_l: ret

.balign 8
.globl __towupper_l
.type __towupper_l, @function
__towupper_l: ret

.balign 8
.globl __uselocale
.type __uselocale, @function
__uselocale: ret

.balign 8
.globl __vsnprintf_chk
.type __vsnprintf_chk, @function
__vsnprintf_chk: ret

.balign 8
.globl __wcscoll_l
.type __wcscoll_l, @function
__wcscoll_l: ret

.balign 8
.globl __wcsftime_l
.type __wcsftime_l, @function
__wcsftime_l: ret

.balign 8
.globl __wcsxfrm_l
.type __wcsxfrm_l, @function
__wcsxfrm_l: ret

.balign 8
.globl __wctype_l
.type __wctype_l, @function
__wctype_l: ret

.balign 8
.globl __wmemcpy_chk
.type __wmemcpy_chk, @function
__wmemcpy_chk: ret

.balign 8
.globl __wmemset_chk
.type __wmemset_chk, @function
__wmemset_chk: ret

.balign 8
.globl __xpg_strerror_r
.type __xpg_strerror_r, @function
__xpg_strerror_r: ret

.balign 8
.globl __xstat
.type __xstat, @function
__xstat: ret

.balign 8
.globl __xstat64
.type __xstat64, @function
__xstat64: ret

.balign 8
.globl _exit
.type _exit, @function
_exit: ret

.balign 8
.globl abort
.type abort, @function
abort: ret

.balign 8
.globl accept4
.type accept4, @function
accept4: ret

.balign 8
.globl access
.type access, @function
access: ret

.balign 8
.globl aligned_alloc
.type aligned_alloc, @function
aligned_alloc: ret

.balign 8
.globl alphasort
.type alphasort, @function
alphasort: ret

.balign 8
.globl arc4random
.type arc4random, @function
arc4random: ret

.balign 8
.globl backtrace
.type backtrace, @function
backtrace: ret

.balign 8
.globl backtrace_symbols
.type backtrace_symbols, @function
backtrace_symbols: ret

.balign 8
.globl bcmp
.type bcmp, @function
bcmp: ret

.balign 8
.globl bind
.type bind, @function
bind: ret

.balign 8
.globl bind_textdomain_codeset
.type bind_textdomain_codeset, @function
bind_textdomain_codeset: ret

.balign 8
.globl bindtextdomain
.type bindtextdomain, @function
bindtextdomain: ret

.balign 8
.globl btowc
.type btowc, @function
btowc: ret

.balign 8
.globl calloc
.type calloc, @function
calloc: ret

.balign 8
.globl chdir
.type chdir, @function
chdir: ret

.balign 8
.globl chmod
.type chmod, @function
chmod: ret

.balign 8
.globl chown
.type chown, @function
chown: ret

.balign 8
.globl chroot
.type chroot, @function
chroot: ret

.balign 8
.globl clearerr
.type clearerr, @function
clearerr: ret

.balign 8
.globl clock
.type clock, @function
clock: ret

.balign 8
.globl __pin_clock_gettime
.type __pin_clock_gettime, @function
__pin_clock_gettime: ret
.symver __pin_clock_gettime, clock_gettime@@GLIBC_2.17, remove

.balign 8
.globl __pin_clock_nanosleep
.type __pin_clock_nanosleep, @function
__pin_clock_nanosleep: ret
.symver __pin_clock_nanosleep, clock_nanosleep@@GLIBC_2.17, remove

.balign 8
.globl close
.type close, @function
close: ret

.balign 8
.globl closedir
.type closedir, @function
closedir: ret

.balign 8
.globl connect
.type connect, @function
connect: ret

.balign 8
.globl dgettext
.type dgettext, @function
dgettext: ret

.balign 8
.globl dirfd
.type dirfd, @function
dirfd: ret

.balign 8
.globl dl_iterate_phdr
.type dl_iterate_phdr, @function
dl_iterate_phdr: ret

.balign 8
.globl __pin_dladdr
.type __pin_dladdr, @function
__pin_dladdr: ret
.symver __pin_dladdr, dladdr@@GLIBC_2.34, remove

.balign 8
.globl __pin_dlclose
.type __pin_dlclose, @function
__pin_dlclose: ret
.symver __pin_dlclose, dlclose@@GLIBC_2.34, remove

.balign 8
.globl __pin_dlerror
.type __pin_dlerror, @function
__pin_dlerror: ret
.symver __pin_dlerror, dlerror@@GLIBC_2.34, remove

.balign 8
.globl __pin_dlopen
.type __pin_dlopen, @function
__pin_dlopen: ret
.symver __pin_dlopen, dlopen@@GLIBC_2.34, remove

.balign 8
.globl __pin_dlsym
.type __pin_dlsym, @function
__pin_dlsym: ret
.symver __pin_dlsym, dlsym@@GLIBC_2.34, remove

.balign 8
.globl dup
.type dup, @function
dup: ret

.balign 8
.globl dup2
.type dup2, @function
dup2: ret

.balign 8
.globl execvp
.type execvp, @function
execvp: ret

.balign 8
.globl exit
.type exit, @function
exit: ret

.balign 8
.globl fchmod
.type fchmod, @function
fchmod: ret

.balign 8
.globl fchmodat
.type fchmodat, @function
fchmodat: ret

.balign 8
.globl fchown
.type fchown, @function
fchown: ret

.balign 8
.globl fclose
.type fclose, @function
fclose: ret

.balign 8
.globl fcntl
.type fcntl, @function
fcntl: ret

.balign 8
.globl fdatasync
.type fdatasync, @function
fdatasync: ret

.balign 8
.globl fdopen
.type fdopen, @function
fdopen: ret

.balign 8
.globl fdopendir
.type fdopendir, @function
fdopendir: ret

.balign 8
.globl ferror
.type ferror, @function
ferror: ret

.balign 8
.globl fflush
.type fflush, @function
fflush: ret

.balign 8
.globl fgetpos64
.type fgetpos64, @function
fgetpos64: ret

.balign 8
.globl fgets
.type fgets, @function
fgets: ret

.balign 8
.globl fileno
.type fileno, @function
fileno: ret

.balign 8
.globl flock
.type flock, @function
flock: ret

.balign 8
.globl fnmatch
.type fnmatch, @function
fnmatch: ret

.balign 8
.globl fopen
.type fopen, @function
fopen: ret

.balign 8
.globl fopen64
.type fopen64, @function
fopen64: ret

.balign 8
.globl fork
.type fork, @function
fork: ret

.balign 8
.globl fprintf
.type fprintf, @function
fprintf: ret

.balign 8
.globl fputc
.type fputc, @function
fputc: ret

.balign 8
.globl fputs
.type fputs, @function
fputs: ret

.balign 8
.globl fread
.type fread, @function
fread: ret

.balign 8
.globl free
.type free, @function
free: ret

.balign 8
.globl freeaddrinfo
.type freeaddrinfo, @function
freeaddrinfo: ret

.balign 8
.globl freelocale
.type freelocale, @function
freelocale: ret

.balign 8
.globl freopen64
.type freopen64, @function
freopen64: ret

.balign 8
.globl fseek
.type fseek, @function
fseek: ret

.balign 8
.globl fseeko
.type fseeko, @function
fseeko: ret

.balign 8
.globl fseeko64
.type fseeko64, @function
fseeko64: ret

.balign 8
.globl fstat
.type fstat, @function
fstat: ret

.balign 8
.globl fstat64
.type fstat64, @function
fstat64: ret

.balign 8
.globl fstatat64
.type fstatat64, @function
fstatat64: ret

.balign 8
.globl fsync
.type fsync, @function
fsync: ret

.balign 8
.globl ftello
.type ftello, @function
ftello: ret

.balign 8
.globl ftello64
.type ftello64, @function
ftello64: ret

.balign 8
.globl ftruncate
.type ftruncate, @function
ftruncate: ret

.balign 8
.globl ftruncate64
.type ftruncate64, @function
ftruncate64: ret

.balign 8
.globl futimens
.type futimens, @function
futimens: ret

.balign 8
.globl fwrite
.type fwrite, @function
fwrite: ret

.balign 8
.globl gai_strerror
.type gai_strerror, @function
gai_strerror: ret

.balign 8
.globl get_nprocs
.type get_nprocs, @function
get_nprocs: ret

.balign 8
.globl getaddrinfo
.type getaddrinfo, @function
getaddrinfo: ret

.balign 8
.globl getauxval
.type getauxval, @function
getauxval: ret

.balign 8
.globl getc
.type getc, @function
getc: ret

.balign 8
.globl getcwd
.type getcwd, @function
getcwd: ret

.balign 8
.globl getentropy
.type getentropy, @function
getentropy: ret

.balign 8
.globl getenv
.type getenv, @function
getenv: ret

.balign 8
.globl gethostname
.type gethostname, @function
gethostname: ret

.balign 8
.globl getpeername
.type getpeername, @function
getpeername: ret

.balign 8
.globl getpid
.type getpid, @function
getpid: ret

.balign 8
.globl getppid
.type getppid, @function
getppid: ret

.balign 8
.globl getpwuid_r
.type getpwuid_r, @function
getpwuid_r: ret

.balign 8
.globl getrlimit
.type getrlimit, @function
getrlimit: ret

.balign 8
.globl getrusage
.type getrusage, @function
getrusage: ret

.balign 8
.globl getsockname
.type getsockname, @function
getsockname: ret

.balign 8
.globl getsockopt
.type getsockopt, @function
getsockopt: ret

.balign 8
.globl gettext
.type gettext, @function
gettext: ret

.balign 8
.globl gettimeofday
.type gettimeofday, @function
gettimeofday: ret

.balign 8
.globl getuid
.type getuid, @function
getuid: ret

.balign 8
.globl getwc
.type getwc, @function
getwc: ret

.balign 8
.globl gmtime_r
.type gmtime_r, @function
gmtime_r: ret

.balign 8
.globl gnu_get_libc_version
.type gnu_get_libc_version, @function
gnu_get_libc_version: ret

.balign 8
.globl iconv
.type iconv, @function
iconv: ret

.balign 8
.globl iconv_close
.type iconv_close, @function
iconv_close: ret

.balign 8
.globl iconv_open
.type iconv_open, @function
iconv_open: ret

.balign 8
.globl inotify_add_watch
.type inotify_add_watch, @function
inotify_add_watch: ret

.balign 8
.globl inotify_init1
.type inotify_init1, @function
inotify_init1: ret

.balign 8
.globl ioctl
.type ioctl, @function
ioctl: ret

.balign 8
.globl isalnum
.type isalnum, @function
isalnum: ret

.balign 8
.globl isalpha
.type isalpha, @function
isalpha: ret

.balign 8
.globl isatty
.type isatty, @function
isatty: ret

.balign 8
.globl isspace
.type isspace, @function
isspace: ret

.balign 8
.globl isxdigit
.type isxdigit, @function
isxdigit: ret

.balign 8
.globl kill
.type kill, @function
kill: ret

.balign 8
.globl killpg
.type killpg, @function
killpg: ret

.balign 8
.globl lchown
.type lchown, @function
lchown: ret

.balign 8
.globl link
.type link, @function
link: ret

.balign 8
.globl linkat
.type linkat, @function
linkat: ret

.balign 8
.globl listen
.type listen, @function
listen: ret

.balign 8
.globl localtime
.type localtime, @function
localtime: ret

.balign 8
.globl localtime_r
.type localtime_r, @function
localtime_r: ret

.balign 8
.globl lseek
.type lseek, @function
lseek: ret

.balign 8
.globl lseek64
.type lseek64, @function
lseek64: ret

.balign 8
.globl lstat
.type lstat, @function
lstat: ret

.balign 8
.globl lstat64
.type lstat64, @function
lstat64: ret

.balign 8
.globl malloc
.type malloc, @function
malloc: ret

.balign 8
.globl mbrtowc
.type mbrtowc, @function
mbrtowc: ret

.balign 8
.globl mbsnrtowcs
.type mbsnrtowcs, @function
mbsnrtowcs: ret

.balign 8
.globl mbstowcs
.type mbstowcs, @function
mbstowcs: ret

.balign 8
.globl memchr
.type memchr, @function
memchr: ret

.balign 8
.globl memcmp
.type memcmp, @function
memcmp: ret

.balign 8
.globl __pin_memcpy
.type __pin_memcpy, @function
__pin_memcpy: ret
.symver __pin_memcpy, memcpy@@GLIBC_2.14, remove

.balign 8
.globl memfd_create
.type memfd_create, @function
memfd_create: ret

.balign 8
.globl memmove
.type memmove, @function
memmove: ret

.balign 8
.globl memset
.type memset, @function
memset: ret

.balign 8
.globl mkdir
.type mkdir, @function
mkdir: ret

.balign 8
.globl mkfifo
.type mkfifo, @function
mkfifo: ret

.balign 8
.globl mkostemp
.type mkostemp, @function
mkostemp: ret

.balign 8
.globl mkstemp
.type mkstemp, @function
mkstemp: ret

.balign 8
.globl mktime
.type mktime, @function
mktime: ret

.balign 8
.globl mmap
.type mmap, @function
mmap: ret

.balign 8
.globl mmap64
.type mmap64, @function
mmap64: ret

.balign 8
.globl mprotect
.type mprotect, @function
mprotect: ret

.balign 8
.globl munmap
.type munmap, @function
munmap: ret

.balign 8
.globl nanosleep
.type nanosleep, @function
nanosleep: ret

.balign 8
.globl newlocale
.type newlocale, @function
newlocale: ret

.balign 8
.globl __pin_nftw
.type __pin_nftw, @function
__pin_nftw: ret
.symver __pin_nftw, nftw@@GLIBC_2.3.3, remove

.balign 8
.globl nl_langinfo
.type nl_langinfo, @function
nl_langinfo: ret

.balign 8
.globl open
.type open, @function
open: ret

.balign 8
.globl open64
.type open64, @function
open64: ret

.balign 8
.globl openat
.type openat, @function
openat: ret

.balign 8
.globl openat64
.type openat64, @function
openat64: ret

.balign 8
.globl opendir
.type opendir, @function
opendir: ret

.balign 8
.globl pause
.type pause, @function
pause: ret

.balign 8
.globl perror
.type perror, @function
perror: ret

.balign 8
.globl pipe
.type pipe, @function
pipe: ret

.balign 8
.globl pipe2
.type pipe2, @function
pipe2: ret

.balign 8
.globl poll
.type poll, @function
poll: ret

.balign 8
.globl posix_fallocate
.type posix_fallocate, @function
posix_fallocate: ret

.balign 8
.globl posix_memalign
.type posix_memalign, @function
posix_memalign: ret

.balign 8
.globl __pin_posix_spawn
.type __pin_posix_spawn, @function
__pin_posix_spawn: ret
.symver __pin_posix_spawn, posix_spawn@@GLIBC_2.15, remove

.balign 8
.globl posix_spawn_file_actions_addclose
.type posix_spawn_file_actions_addclose, @function
posix_spawn_file_actions_addclose: ret

.balign 8
.globl posix_spawn_file_actions_adddup2
.type posix_spawn_file_actions_adddup2, @function
posix_spawn_file_actions_adddup2: ret

.balign 8
.globl posix_spawn_file_actions_addopen
.type posix_spawn_file_actions_addopen, @function
posix_spawn_file_actions_addopen: ret

.balign 8
.globl posix_spawn_file_actions_destroy
.type posix_spawn_file_actions_destroy, @function
posix_spawn_file_actions_destroy: ret

.balign 8
.globl posix_spawn_file_actions_init
.type posix_spawn_file_actions_init, @function
posix_spawn_file_actions_init: ret

.balign 8
.globl posix_spawnattr_destroy
.type posix_spawnattr_destroy, @function
posix_spawnattr_destroy: ret

.balign 8
.globl posix_spawnattr_getflags
.type posix_spawnattr_getflags, @function
posix_spawnattr_getflags: ret

.balign 8
.globl posix_spawnattr_init
.type posix_spawnattr_init, @function
posix_spawnattr_init: ret

.balign 8
.globl posix_spawnattr_setflags
.type posix_spawnattr_setflags, @function
posix_spawnattr_setflags: ret

.balign 8
.globl posix_spawnattr_setpgroup
.type posix_spawnattr_setpgroup, @function
posix_spawnattr_setpgroup: ret

.balign 8
.globl posix_spawnattr_setsigdefault
.type posix_spawnattr_setsigdefault, @function
posix_spawnattr_setsigdefault: ret

.balign 8
.globl __pin_posix_spawnp
.type __pin_posix_spawnp, @function
__pin_posix_spawnp: ret
.symver __pin_posix_spawnp, posix_spawnp@@GLIBC_2.15, remove

.balign 8
.globl pread64
.type pread64, @function
pread64: ret

.balign 8
.globl preadv
.type preadv, @function
preadv: ret

.balign 8
.globl printf
.type printf, @function
printf: ret

.balign 8
.globl pthread_attr_destroy
.type pthread_attr_destroy, @function
pthread_attr_destroy: ret

.balign 8
.globl __pin_pthread_attr_getguardsize
.type __pin_pthread_attr_getguardsize, @function
__pin_pthread_attr_getguardsize: ret
.symver __pin_pthread_attr_getguardsize, pthread_attr_getguardsize@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_attr_getstack
.type __pin_pthread_attr_getstack, @function
__pin_pthread_attr_getstack: ret
.symver __pin_pthread_attr_getstack, pthread_attr_getstack@@GLIBC_2.34, remove

.balign 8
.globl pthread_attr_init
.type pthread_attr_init, @function
pthread_attr_init: ret

.balign 8
.globl pthread_attr_setdetachstate
.type pthread_attr_setdetachstate, @function
pthread_attr_setdetachstate: ret

.balign 8
.globl __pin_pthread_attr_setstacksize
.type __pin_pthread_attr_setstacksize, @function
__pin_pthread_attr_setstacksize: ret
.symver __pin_pthread_attr_setstacksize, pthread_attr_setstacksize@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_cond_broadcast
.type __pin_pthread_cond_broadcast, @function
__pin_pthread_cond_broadcast: ret
.symver __pin_pthread_cond_broadcast, pthread_cond_broadcast@@GLIBC_2.3.2, remove

.balign 8
.globl __pin_pthread_cond_destroy
.type __pin_pthread_cond_destroy, @function
__pin_pthread_cond_destroy: ret
.symver __pin_pthread_cond_destroy, pthread_cond_destroy@@GLIBC_2.3.2, remove

.balign 8
.globl __pin_pthread_cond_init
.type __pin_pthread_cond_init, @function
__pin_pthread_cond_init: ret
.symver __pin_pthread_cond_init, pthread_cond_init@@GLIBC_2.3.2, remove

.balign 8
.globl __pin_pthread_cond_signal
.type __pin_pthread_cond_signal, @function
__pin_pthread_cond_signal: ret
.symver __pin_pthread_cond_signal, pthread_cond_signal@@GLIBC_2.3.2, remove

.balign 8
.globl __pin_pthread_cond_timedwait
.type __pin_pthread_cond_timedwait, @function
__pin_pthread_cond_timedwait: ret
.symver __pin_pthread_cond_timedwait, pthread_cond_timedwait@@GLIBC_2.3.2, remove

.balign 8
.globl __pin_pthread_cond_wait
.type __pin_pthread_cond_wait, @function
__pin_pthread_cond_wait: ret
.symver __pin_pthread_cond_wait, pthread_cond_wait@@GLIBC_2.3.2, remove

.balign 8
.globl __pin_pthread_create
.type __pin_pthread_create, @function
__pin_pthread_create: ret
.symver __pin_pthread_create, pthread_create@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_detach
.type __pin_pthread_detach, @function
__pin_pthread_detach: ret
.symver __pin_pthread_detach, pthread_detach@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_getattr_np
.type __pin_pthread_getattr_np, @function
__pin_pthread_getattr_np: ret
.symver __pin_pthread_getattr_np, pthread_getattr_np@@GLIBC_2.32, remove

.balign 8
.globl pthread_getschedparam
.type pthread_getschedparam, @function
pthread_getschedparam: ret

.balign 8
.globl __pin_pthread_getspecific
.type __pin_pthread_getspecific, @function
__pin_pthread_getspecific: ret
.symver __pin_pthread_getspecific, pthread_getspecific@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_join
.type __pin_pthread_join, @function
__pin_pthread_join: ret
.symver __pin_pthread_join, pthread_join@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_key_create
.type __pin_pthread_key_create, @function
__pin_pthread_key_create: ret
.symver __pin_pthread_key_create, pthread_key_create@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_key_delete
.type __pin_pthread_key_delete, @function
__pin_pthread_key_delete: ret
.symver __pin_pthread_key_delete, pthread_key_delete@@GLIBC_2.34, remove

.balign 8
.globl pthread_mutex_destroy
.type pthread_mutex_destroy, @function
pthread_mutex_destroy: ret

.balign 8
.globl pthread_mutex_init
.type pthread_mutex_init, @function
pthread_mutex_init: ret

.balign 8
.globl pthread_mutex_lock
.type pthread_mutex_lock, @function
pthread_mutex_lock: ret

.balign 8
.globl __pin_pthread_mutex_trylock
.type __pin_pthread_mutex_trylock, @function
__pin_pthread_mutex_trylock: ret
.symver __pin_pthread_mutex_trylock, pthread_mutex_trylock@@GLIBC_2.34, remove

.balign 8
.globl pthread_mutex_unlock
.type pthread_mutex_unlock, @function
pthread_mutex_unlock: ret

.balign 8
.globl __pin_pthread_mutexattr_init
.type __pin_pthread_mutexattr_init, @function
__pin_pthread_mutexattr_init: ret
.symver __pin_pthread_mutexattr_init, pthread_mutexattr_init@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_mutexattr_settype
.type __pin_pthread_mutexattr_settype, @function
__pin_pthread_mutexattr_settype: ret
.symver __pin_pthread_mutexattr_settype, pthread_mutexattr_settype@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_once
.type __pin_pthread_once, @function
__pin_pthread_once: ret
.symver __pin_pthread_once, pthread_once@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_destroy
.type __pin_pthread_rwlock_destroy, @function
__pin_pthread_rwlock_destroy: ret
.symver __pin_pthread_rwlock_destroy, pthread_rwlock_destroy@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_init
.type __pin_pthread_rwlock_init, @function
__pin_pthread_rwlock_init: ret
.symver __pin_pthread_rwlock_init, pthread_rwlock_init@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_rdlock
.type __pin_pthread_rwlock_rdlock, @function
__pin_pthread_rwlock_rdlock: ret
.symver __pin_pthread_rwlock_rdlock, pthread_rwlock_rdlock@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_tryrdlock
.type __pin_pthread_rwlock_tryrdlock, @function
__pin_pthread_rwlock_tryrdlock: ret
.symver __pin_pthread_rwlock_tryrdlock, pthread_rwlock_tryrdlock@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_trywrlock
.type __pin_pthread_rwlock_trywrlock, @function
__pin_pthread_rwlock_trywrlock: ret
.symver __pin_pthread_rwlock_trywrlock, pthread_rwlock_trywrlock@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_unlock
.type __pin_pthread_rwlock_unlock, @function
__pin_pthread_rwlock_unlock: ret
.symver __pin_pthread_rwlock_unlock, pthread_rwlock_unlock@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_rwlock_wrlock
.type __pin_pthread_rwlock_wrlock, @function
__pin_pthread_rwlock_wrlock: ret
.symver __pin_pthread_rwlock_wrlock, pthread_rwlock_wrlock@@GLIBC_2.34, remove

.balign 8
.globl pthread_self
.type pthread_self, @function
pthread_self: ret

.balign 8
.globl pthread_setcanceltype
.type pthread_setcanceltype, @function
pthread_setcanceltype: ret

.balign 8
.globl __pin_pthread_setname_np
.type __pin_pthread_setname_np, @function
__pin_pthread_setname_np: ret
.symver __pin_pthread_setname_np, pthread_setname_np@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_setspecific
.type __pin_pthread_setspecific, @function
__pin_pthread_setspecific: ret
.symver __pin_pthread_setspecific, pthread_setspecific@@GLIBC_2.34, remove

.balign 8
.globl __pin_pthread_sigmask
.type __pin_pthread_sigmask, @function
__pin_pthread_sigmask: ret
.symver __pin_pthread_sigmask, pthread_sigmask@@GLIBC_2.32, remove

.balign 8
.globl putc
.type putc, @function
putc: ret

.balign 8
.globl putchar
.type putchar, @function
putchar: ret

.balign 8
.globl puts
.type puts, @function
puts: ret

.balign 8
.globl putwc
.type putwc, @function
putwc: ret

.balign 8
.globl pwrite64
.type pwrite64, @function
pwrite64: ret

.balign 8
.globl pwritev
.type pwritev, @function
pwritev: ret

.balign 8
.globl qsort
.type qsort, @function
qsort: ret

.balign 8
.globl qsort_r
.type qsort_r, @function
qsort_r: ret

.balign 8
.globl raise
.type raise, @function
raise: ret

.balign 8
.globl rand
.type rand, @function
rand: ret

.balign 8
.globl read
.type read, @function
read: ret

.balign 8
.globl readdir
.type readdir, @function
readdir: ret

.balign 8
.globl readdir64
.type readdir64, @function
readdir64: ret

.balign 8
.globl readlink
.type readlink, @function
readlink: ret

.balign 8
.globl readv
.type readv, @function
readv: ret

.balign 8
.globl realloc
.type realloc, @function
realloc: ret

.balign 8
.globl __pin_realpath
.type __pin_realpath, @function
__pin_realpath: ret
.symver __pin_realpath, realpath@@GLIBC_2.3, remove

.balign 8
.globl recv
.type recv, @function
recv: ret

.balign 8
.globl recvfrom
.type recvfrom, @function
recvfrom: ret

.balign 8
.globl recvmsg
.type recvmsg, @function
recvmsg: ret

.balign 8
.globl remove
.type remove, @function
remove: ret

.balign 8
.globl rename
.type rename, @function
rename: ret

.balign 8
.globl rmdir
.type rmdir, @function
rmdir: ret

.balign 8
.globl scandir
.type scandir, @function
scandir: ret

.balign 8
.globl __pin_sched_getaffinity
.type __pin_sched_getaffinity, @function
__pin_sched_getaffinity: ret
.symver __pin_sched_getaffinity, sched_getaffinity@@GLIBC_2.3.4, remove

.balign 8
.globl sched_getparam
.type sched_getparam, @function
sched_getparam: ret

.balign 8
.globl sched_getscheduler
.type sched_getscheduler, @function
sched_getscheduler: ret

.balign 8
.globl sched_setscheduler
.type sched_setscheduler, @function
sched_setscheduler: ret

.balign 8
.globl sched_yield
.type sched_yield, @function
sched_yield: ret

.balign 8
.globl secure_getenv
.type secure_getenv, @function
secure_getenv: ret

.balign 8
.globl select
.type select, @function
select: ret

.balign 8
.globl __pin_sem_destroy
.type __pin_sem_destroy, @function
__pin_sem_destroy: ret
.symver __pin_sem_destroy, sem_destroy@@GLIBC_2.34, remove

.balign 8
.globl __pin_sem_getvalue
.type __pin_sem_getvalue, @function
__pin_sem_getvalue: ret
.symver __pin_sem_getvalue, sem_getvalue@@GLIBC_2.34, remove

.balign 8
.globl __pin_sem_init
.type __pin_sem_init, @function
__pin_sem_init: ret
.symver __pin_sem_init, sem_init@@GLIBC_2.34, remove

.balign 8
.globl __pin_sem_post
.type __pin_sem_post, @function
__pin_sem_post: ret
.symver __pin_sem_post, sem_post@@GLIBC_2.34, remove

.balign 8
.globl __pin_sem_timedwait
.type __pin_sem_timedwait, @function
__pin_sem_timedwait: ret
.symver __pin_sem_timedwait, sem_timedwait@@GLIBC_2.34, remove

.balign 8
.globl __pin_sem_trywait
.type __pin_sem_trywait, @function
__pin_sem_trywait: ret
.symver __pin_sem_trywait, sem_trywait@@GLIBC_2.34, remove

.balign 8
.globl __pin_sem_wait
.type __pin_sem_wait, @function
__pin_sem_wait: ret
.symver __pin_sem_wait, sem_wait@@GLIBC_2.34, remove

.balign 8
.globl send
.type send, @function
send: ret

.balign 8
.globl sendfile
.type sendfile, @function
sendfile: ret

.balign 8
.globl sendfile64
.type sendfile64, @function
sendfile64: ret

.balign 8
.globl sendmsg
.type sendmsg, @function
sendmsg: ret

.balign 8
.globl sendto
.type sendto, @function
sendto: ret

.balign 8
.globl setenv
.type setenv, @function
setenv: ret

.balign 8
.globl setgid
.type setgid, @function
setgid: ret

.balign 8
.globl setgroups
.type setgroups, @function
setgroups: ret

.balign 8
.globl setlocale
.type setlocale, @function
setlocale: ret

.balign 8
.globl setpgid
.type setpgid, @function
setpgid: ret

.balign 8
.globl setpriority
.type setpriority, @function
setpriority: ret

.balign 8
.globl setrlimit
.type setrlimit, @function
setrlimit: ret

.balign 8
.globl setsid
.type setsid, @function
setsid: ret

.balign 8
.globl setsockopt
.type setsockopt, @function
setsockopt: ret

.balign 8
.globl setuid
.type setuid, @function
setuid: ret

.balign 8
.globl setvbuf
.type setvbuf, @function
setvbuf: ret

.balign 8
.globl shmat
.type shmat, @function
shmat: ret

.balign 8
.globl shmctl
.type shmctl, @function
shmctl: ret

.balign 8
.globl shmdt
.type shmdt, @function
shmdt: ret

.balign 8
.globl shmget
.type shmget, @function
shmget: ret

.balign 8
.globl shutdown
.type shutdown, @function
shutdown: ret

.balign 8
.globl sigaction
.type sigaction, @function
sigaction: ret

.balign 8
.globl sigaddset
.type sigaddset, @function
sigaddset: ret

.balign 8
.globl sigaltstack
.type sigaltstack, @function
sigaltstack: ret

.balign 8
.globl sigemptyset
.type sigemptyset, @function
sigemptyset: ret

.balign 8
.globl signal
.type signal, @function
signal: ret

.balign 8
.globl sigprocmask
.type sigprocmask, @function
sigprocmask: ret

.balign 8
.globl sigtimedwait
.type sigtimedwait, @function
sigtimedwait: ret

.balign 8
.globl snprintf
.type snprintf, @function
snprintf: ret

.balign 8
.globl socket
.type socket, @function
socket: ret

.balign 8
.globl socketpair
.type socketpair, @function
socketpair: ret

.balign 8
.globl splice
.type splice, @function
splice: ret

.balign 8
.globl sprintf
.type sprintf, @function
sprintf: ret

.balign 8
.globl srand
.type srand, @function
srand: ret

.balign 8
.globl stat
.type stat, @function
stat: ret

.balign 8
.globl stat64
.type stat64, @function
stat64: ret

.balign 8
.globl statvfs
.type statvfs, @function
statvfs: ret

.balign 8
.globl stpcpy
.type stpcpy, @function
stpcpy: ret

.balign 8
.globl strchr
.type strchr, @function
strchr: ret

.balign 8
.globl strcmp
.type strcmp, @function
strcmp: ret

.balign 8
.globl strcpy
.type strcpy, @function
strcpy: ret

.balign 8
.globl strdup
.type strdup, @function
strdup: ret

.balign 8
.globl strerror
.type strerror, @function
strerror: ret

.balign 8
.globl strerror_r
.type strerror_r, @function
strerror_r: ret

.balign 8
.globl strfromf128
.type strfromf128, @function
strfromf128: ret

.balign 8
.globl strlcat
.type strlcat, @function
strlcat: ret

.balign 8
.globl strlcpy
.type strlcpy, @function
strlcpy: ret

.balign 8
.globl strlen
.type strlen, @function
strlen: ret

.balign 8
.globl strncmp
.type strncmp, @function
strncmp: ret

.balign 8
.globl strncpy
.type strncpy, @function
strncpy: ret

.balign 8
.globl strnlen
.type strnlen, @function
strnlen: ret

.balign 8
.globl strpbrk
.type strpbrk, @function
strpbrk: ret

.balign 8
.globl strrchr
.type strrchr, @function
strrchr: ret

.balign 8
.globl strspn
.type strspn, @function
strspn: ret

.balign 8
.globl strstr
.type strstr, @function
strstr: ret

.balign 8
.globl strtod
.type strtod, @function
strtod: ret

.balign 8
.globl strtof
.type strtof, @function
strtof: ret

.balign 8
.globl strtof128
.type strtof128, @function
strtof128: ret

.balign 8
.globl strtok_r
.type strtok_r, @function
strtok_r: ret

.balign 8
.globl strtol
.type strtol, @function
strtol: ret

.balign 8
.globl strtold
.type strtold, @function
strtold: ret

.balign 8
.globl strtold_l
.type strtold_l, @function
strtold_l: ret

.balign 8
.globl strtoll
.type strtoll, @function
strtoll: ret

.balign 8
.globl strtoul
.type strtoul, @function
strtoul: ret

.balign 8
.globl strtoull
.type strtoull, @function
strtoull: ret

.balign 8
.globl symlink
.type symlink, @function
symlink: ret

.balign 8
.globl syscall
.type syscall, @function
syscall: ret

.balign 8
.globl sysconf
.type sysconf, @function
sysconf: ret

.balign 8
.globl time
.type time, @function
time: ret

.balign 8
.globl tolower
.type tolower, @function
tolower: ret

.balign 8
.globl toupper
.type toupper, @function
toupper: ret

.balign 8
.globl truncate
.type truncate, @function
truncate: ret

.balign 8
.globl ungetc
.type ungetc, @function
ungetc: ret

.balign 8
.globl ungetwc
.type ungetwc, @function
ungetwc: ret

.balign 8
.globl unlink
.type unlink, @function
unlink: ret

.balign 8
.globl unlinkat
.type unlinkat, @function
unlinkat: ret

.balign 8
.globl unsetenv
.type unsetenv, @function
unsetenv: ret

.balign 8
.globl uselocale
.type uselocale, @function
uselocale: ret

.balign 8
.globl usleep
.type usleep, @function
usleep: ret

.balign 8
.globl utime
.type utime, @function
utime: ret

.balign 8
.globl utimensat
.type utimensat, @function
utimensat: ret

.balign 8
.globl vfork
.type vfork, @function
vfork: ret

.balign 8
.globl vsnprintf
.type vsnprintf, @function
vsnprintf: ret

.balign 8
.globl waitid
.type waitid, @function
waitid: ret

.balign 8
.globl waitpid
.type waitpid, @function
waitpid: ret

.balign 8
.globl wcrtomb
.type wcrtomb, @function
wcrtomb: ret

.balign 8
.globl wcscmp
.type wcscmp, @function
wcscmp: ret

.balign 8
.globl wcsdup
.type wcsdup, @function
wcsdup: ret

.balign 8
.globl wcslcat
.type wcslcat, @function
wcslcat: ret

.balign 8
.globl wcslcpy
.type wcslcpy, @function
wcslcpy: ret

.balign 8
.globl wcslen
.type wcslen, @function
wcslen: ret

.balign 8
.globl wcsncmp
.type wcsncmp, @function
wcsncmp: ret

.balign 8
.globl wcsncpy
.type wcsncpy, @function
wcsncpy: ret

.balign 8
.globl wcsnlen
.type wcsnlen, @function
wcsnlen: ret

.balign 8
.globl wcsnrtombs
.type wcsnrtombs, @function
wcsnrtombs: ret

.balign 8
.globl wcsstr
.type wcsstr, @function
wcsstr: ret

.balign 8
.globl wctob
.type wctob, @function
wctob: ret

.balign 8
.globl wmemchr
.type wmemchr, @function
wmemchr: ret

.balign 8
.globl wmemcmp
.type wmemcmp, @function
wmemcmp: ret

.balign 8
.globl wmemcpy
.type wmemcpy, @function
wmemcpy: ret

.balign 8
.globl wmemmove
.type wmemmove, @function
wmemmove: ret

.balign 8
.globl wmemset
.type wmemset, @function
wmemset: ret

.balign 8
.globl write
.type write, @function
write: ret

.balign 8
.globl writev
.type writev, @function
writev: ret

.section .bss
.balign 8
.globl __libc_single_threaded
.type __libc_single_threaded, @object
.size __libc_single_threaded, 1
__libc_single_threaded: .skip 1

.balign 8
.globl environ
.type environ, @object
.size environ, 8
environ: .skip 8

.section .data
.balign 8
.globl stderr
.type stderr, @object
.size stderr, 8
stderr: .skip 8

.balign 8
.globl stdin
.type stdin, @object
.size stdin, 8
stdin: .skip 8

.balign 8
.globl stdout
.type stdout, @object
.size stdout, 8
stdout: .skip 8

