# Stub shared object for libgcc_s.so.1. Generated by stubs/generate.sh.
#
# Declares the symbols the host archive leaves undefined, so the link
# resolves and the executable records libgcc_s.so.1 as a plain DT_NEEDED. The
# real library provides every implementation at run time. No .symver
# anywhere: a versioned reference would pin the executable to a
# GLIBC_2.xx the player may not have.
#
# glibc floor: 2.39. Toolchain: built_with_toolchain.txt.

.text
.balign 8
.globl _Unwind_Backtrace
.type _Unwind_Backtrace, @function
_Unwind_Backtrace: ret

.balign 8
.globl _Unwind_DeleteException
.type _Unwind_DeleteException, @function
_Unwind_DeleteException: ret

.balign 8
.globl _Unwind_FindEnclosingFunction
.type _Unwind_FindEnclosingFunction, @function
_Unwind_FindEnclosingFunction: ret

.balign 8
.globl _Unwind_GetCFA
.type _Unwind_GetCFA, @function
_Unwind_GetCFA: ret

.balign 8
.globl _Unwind_GetDataRelBase
.type _Unwind_GetDataRelBase, @function
_Unwind_GetDataRelBase: ret

.balign 8
.globl _Unwind_GetIP
.type _Unwind_GetIP, @function
_Unwind_GetIP: ret

.balign 8
.globl _Unwind_GetIPInfo
.type _Unwind_GetIPInfo, @function
_Unwind_GetIPInfo: ret

.balign 8
.globl _Unwind_GetLanguageSpecificData
.type _Unwind_GetLanguageSpecificData, @function
_Unwind_GetLanguageSpecificData: ret

.balign 8
.globl _Unwind_GetRegionStart
.type _Unwind_GetRegionStart, @function
_Unwind_GetRegionStart: ret

.balign 8
.globl _Unwind_GetTextRelBase
.type _Unwind_GetTextRelBase, @function
_Unwind_GetTextRelBase: ret

.balign 8
.globl _Unwind_RaiseException
.type _Unwind_RaiseException, @function
_Unwind_RaiseException: ret

.balign 8
.globl _Unwind_Resume
.type _Unwind_Resume, @function
_Unwind_Resume: ret

.balign 8
.globl _Unwind_Resume_or_Rethrow
.type _Unwind_Resume_or_Rethrow, @function
_Unwind_Resume_or_Rethrow: ret

.balign 8
.globl _Unwind_SetGR
.type _Unwind_SetGR, @function
_Unwind_SetGR: ret

.balign 8
.globl _Unwind_SetIP
.type _Unwind_SetIP, @function
_Unwind_SetIP: ret

