# Stub shared object for libm.so.6. Generated by stubs/generate.sh.
#
# Declares the symbols the host archive leaves undefined, so the link
# resolves and the executable records libm.so.6 as a plain DT_NEEDED. The
# real library provides every implementation at run time. A symbol
# with a single version stays unversioned and carries no GLIBC_2.xx
# requirement. A symbol the library also exports at a compat version
# carries a .symver pin to the default version: ld.so binds an
# unversioned reference to the oldest version node, which is the
# compat implementation.
#
# glibc floor: 2.39. Toolchain: built_with_toolchain.txt.

.text
.balign 8
.globl acos
.type acos, @function
acos: ret

.balign 8
.globl acosf
.type acosf, @function
acosf: ret

.balign 8
.globl asin
.type asin, @function
asin: ret

.balign 8
.globl asinf
.type asinf, @function
asinf: ret

.balign 8
.globl atan
.type atan, @function
atan: ret

.balign 8
.globl atan2
.type atan2, @function
atan2: ret

.balign 8
.globl atan2f
.type atan2f, @function
atan2f: ret

.balign 8
.globl atanf
.type atanf, @function
atanf: ret

.balign 8
.globl cos
.type cos, @function
cos: ret

.balign 8
.globl cosf
.type cosf, @function
cosf: ret

.balign 8
.globl __pin_exp
.type __pin_exp, @function
__pin_exp: ret
.symver __pin_exp, exp@@GLIBC_2.29, remove

.balign 8
.globl __pin_exp2
.type __pin_exp2, @function
__pin_exp2: ret
.symver __pin_exp2, exp2@@GLIBC_2.29, remove

.balign 8
.globl __pin_exp2f
.type __pin_exp2f, @function
__pin_exp2f: ret
.symver __pin_exp2f, exp2f@@GLIBC_2.27, remove

.balign 8
.globl __pin_expf
.type __pin_expf, @function
__pin_expf: ret
.symver __pin_expf, expf@@GLIBC_2.27, remove

.balign 8
.globl fegetround
.type fegetround, @function
fegetround: ret

.balign 8
.globl fesetround
.type fesetround, @function
fesetround: ret

.balign 8
.globl frexp
.type frexp, @function
frexp: ret

.balign 8
.globl frexpl
.type frexpl, @function
frexpl: ret

.balign 8
.globl __pin_hypotf
.type __pin_hypotf, @function
__pin_hypotf: ret
.symver __pin_hypotf, hypotf@@GLIBC_2.35, remove

.balign 8
.globl ldexp
.type ldexp, @function
ldexp: ret

.balign 8
.globl __pin_log
.type __pin_log, @function
__pin_log: ret
.symver __pin_log, log@@GLIBC_2.29, remove

.balign 8
.globl log10
.type log10, @function
log10: ret

.balign 8
.globl log10f
.type log10f, @function
log10f: ret

.balign 8
.globl __pin_log2
.type __pin_log2, @function
__pin_log2: ret
.symver __pin_log2, log2@@GLIBC_2.29, remove

.balign 8
.globl __pin_logf
.type __pin_logf, @function
__pin_logf: ret
.symver __pin_logf, logf@@GLIBC_2.27, remove

.balign 8
.globl lround
.type lround, @function
lround: ret

.balign 8
.globl lroundf
.type lroundf, @function
lroundf: ret

.balign 8
.globl modf
.type modf, @function
modf: ret

.balign 8
.globl modff
.type modff, @function
modff: ret

.balign 8
.globl __pin_pow
.type __pin_pow, @function
__pin_pow: ret
.symver __pin_pow, pow@@GLIBC_2.29, remove

.balign 8
.globl __pin_powf
.type __pin_powf, @function
__pin_powf: ret
.symver __pin_powf, powf@@GLIBC_2.27, remove

.balign 8
.globl scalbn
.type scalbn, @function
scalbn: ret

.balign 8
.globl scalbnf
.type scalbnf, @function
scalbnf: ret

.balign 8
.globl sin
.type sin, @function
sin: ret

.balign 8
.globl sincos
.type sincos, @function
sincos: ret

.balign 8
.globl sincosf
.type sincosf, @function
sincosf: ret

.balign 8
.globl sinf
.type sinf, @function
sinf: ret

.balign 8
.globl tan
.type tan, @function
tan: ret

.balign 8
.globl tanf
.type tanf, @function
tanf: ret

