# Stub shared object for libm.so.6. Generated by stubs/generate.sh.
#
# Declares the symbols the host archive leaves undefined, so the link
# resolves and the executable records libm.so.6 as a plain DT_NEEDED. The
# real library provides every implementation at run time. No .symver
# anywhere: a versioned reference would pin the executable to a
# GLIBC_2.xx the player may not have.
#
# glibc floor: 2.39. Toolchain: built_with_toolchain.txt.

.text
.balign 8
.globl acos
.type acos, @function
acos: ret

.balign 8
.globl acosf
.type acosf, @function
acosf: ret

.balign 8
.globl asin
.type asin, @function
asin: ret

.balign 8
.globl asinf
.type asinf, @function
asinf: ret

.balign 8
.globl atan
.type atan, @function
atan: ret

.balign 8
.globl atan2
.type atan2, @function
atan2: ret

.balign 8
.globl atan2f
.type atan2f, @function
atan2f: ret

.balign 8
.globl atanf
.type atanf, @function
atanf: ret

.balign 8
.globl cos
.type cos, @function
cos: ret

.balign 8
.globl cosf
.type cosf, @function
cosf: ret

.balign 8
.globl exp
.type exp, @function
exp: ret

.balign 8
.globl exp2
.type exp2, @function
exp2: ret

.balign 8
.globl exp2f
.type exp2f, @function
exp2f: ret

.balign 8
.globl expf
.type expf, @function
expf: ret

.balign 8
.globl fegetround
.type fegetround, @function
fegetround: ret

.balign 8
.globl fesetround
.type fesetround, @function
fesetround: ret

.balign 8
.globl frexp
.type frexp, @function
frexp: ret

.balign 8
.globl frexpl
.type frexpl, @function
frexpl: ret

.balign 8
.globl hypotf
.type hypotf, @function
hypotf: ret

.balign 8
.globl ldexp
.type ldexp, @function
ldexp: ret

.balign 8
.globl log
.type log, @function
log: ret

.balign 8
.globl log10
.type log10, @function
log10: ret

.balign 8
.globl log10f
.type log10f, @function
log10f: ret

.balign 8
.globl log2
.type log2, @function
log2: ret

.balign 8
.globl logf
.type logf, @function
logf: ret

.balign 8
.globl lround
.type lround, @function
lround: ret

.balign 8
.globl lroundf
.type lroundf, @function
lroundf: ret

.balign 8
.globl modf
.type modf, @function
modf: ret

.balign 8
.globl modff
.type modff, @function
modff: ret

.balign 8
.globl pow
.type pow, @function
pow: ret

.balign 8
.globl powf
.type powf, @function
powf: ret

.balign 8
.globl scalbn
.type scalbn, @function
scalbn: ret

.balign 8
.globl scalbnf
.type scalbnf, @function
scalbnf: ret

.balign 8
.globl sin
.type sin, @function
sin: ret

.balign 8
.globl sincos
.type sincos, @function
sincos: ret

.balign 8
.globl sincosf
.type sincosf, @function
sincosf: ret

.balign 8
.globl sinf
.type sinf, @function
sinf: ret

.balign 8
.globl tan
.type tan, @function
tan: ret

.balign 8
.globl tanf
.type tanf, @function
tanf: ret

