# Stub shared object for libvulkan.so.1. Generated by stubs/generate.sh.
#
# Declares the symbols the host archive leaves undefined, so the link
# resolves and the executable records libvulkan.so.1 as a plain DT_NEEDED. The
# real library provides every implementation at run time. No .symver
# anywhere: a versioned reference would pin the executable to a
# GLIBC_2.xx the player may not have.
#
# glibc floor: 2.39. Toolchain: built_with_toolchain.txt.

.text
.balign 8
.globl vkGetInstanceProcAddr
.type vkGetInstanceProcAddr, @function
vkGetInstanceProcAddr: ret

